apps/account/urls.py
from django.urls import path
from apps.account import views
# model

app_name = 'account'

urlpatterns = [
    path('new-account/<int:pk>/', views.CreateAccountView.as_view(), name='new_account'),
    path('calendar/<int:pk>/', views.CalendarView.as_view(), name='calendar')
]

apps/client/urls.py
from django.urls import path
from apps.client import views
# model

app_name = 'client'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('sign-up/', views.SignUpView.as_view(), name='sign_up'),
    path('new-group/', views.NewGroupView.as_view(), name='new_group'),
    path('search-group/', views.ClientSearchGroupListView.as_view(), name='search_groups'),
    path('user-group/<int:pk>/', views.ClientGroupList.as_view(), name='user_groups'),
]

pageyou/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/client/login/')),
    # clientes
    path('client/', include('apps.client.urls')),
    # account
    path('account/', include('apps.account.urls')),
    # api account
    path('api_account/', include('apps.account.api.urls')),
    # catalogs
    path('catalogs/', include('apps.catalog.urls')),  # /api_account/transaction/
]

apps/client/models.py
from django.contrib.auth.models import User
from django.db import models


class Client(models.Model):
    coordinator = models.BooleanField(default=False)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.username

    class Meta:
        permissions = (("coordinator", "Set coordinator group"),)

apps/client/forms.py
from django import forms

# models
from apps.client.models import Client
from django.contrib.auth.models import User, Group


class ClientLoginForm(forms.Form):
    username = forms.CharField(label="Nombre de usuario*",
                               widget=forms.TextInput(attrs={'required': True, 'class': 'field-account'}))
    password = forms.CharField(label="Contraseña*",
                               widget=forms.PasswordInput(attrs={'required': True, 'class': 'field-account'}))


class UserSignUpForm(forms.Form):
    """ Formulario para el registro de usuario """
    username = forms.CharField(label='Nombre de usuario*', min_length=4, max_length=150,
                               widget=forms.TextInput(attrs={'required': True, 'class': 'field-account'}))
    email = forms.EmailField(label='Correo electronico*',
                             widget=forms.TextInput(attrs={'required': True, 'class': 'field-account'}))
    password1 = forms.CharField(label='Contraseña*',
                                widget=forms.PasswordInput(attrs={'required': True, 'class': 'field-account'}))
    password2 = forms.CharField(label='Confirme su Contraseña*',
                                widget=forms.PasswordInput(attrs={'required': True, 'class': 'field-account'}))

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        user_count = User.objects.filter(username=username).count()
        if user_count > 0:
            raise forms.ValidationError("El usuario ya existe")
        else:
            return username

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 != password2:
            raise forms.ValidationError('Las contraseñas no coinciden')
        else:
            return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password1']
        )
        return user


class NewGroupView(forms.Form):
    name = forms.CharField(label='Nombre*',
                           widget=forms.TextInput(attrs={'required': True, 'class': 'field-account'},))

    def clean_name(self):
        name = self.cleaned_data['name']
        group_count = Group.objects.filter(name=name).count()
        if group_count > 0:
            raise forms.ValidationError('El nombre del grupo ya existe')
        else:
            return name

    def save(self):
        group = Group.objects.create(
            name=self.cleaned_data['name'],
        )
        return group

apps/client/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views.generic import FormView, ListView
from django.contrib.auth.models import Group, User, Permission
from utils.constants import Message
# forms
from apps.client.forms import ClientLoginForm, NewGroupView, UserSignUpForm
from apps.client.models import Client
from apps.account.models import Account


class LoginView(SuccessMessageMixin, FormView):
    template_name = 'client/login.html'
    form_class = ClientLoginForm
    success_url = '/client/search-group/'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            """ User authenticate """
            login(self.request, user)
            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.error(self.request, Message.ERROR_LOGIN)
            return self.render_to_response(self.get_context_data(form=form))


@login_required()
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/client/login/')


class SignUpView(SuccessMessageMixin, FormView):
    template_name = 'client/sign_up.html'
    form_class = UserSignUpForm
    # success_message = 'El usuario se creo correctamente'

    def form_valid(self, form):
        user = form.save()
        if form.is_valid():
            """ Save new client """
            client = Client.objects.create(user=user)
            client.save()
            messages.success(self.request, Message.SUCCESS_LOGIN)
        return HttpResponseRedirect('/client/login/')

    def form_invalid(self, form):
        """ Create client error """
        messages.error(self.request, form.errors)
        return self.render_to_response(self.get_context_data(form=form))


class NewGroupView(LoginRequiredMixin, FormView):
    """ Create new group """
    login_url = '/client/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'client/new_group.html'
    form_class = NewGroupView
    success_url = '/client/search-group/'

    def form_valid(self, form):
        """ Assignment of a coordinator to the group """
        group = form.save()  # create new group
        user = User.objects.get(username=self.request.user)  # get user
        client = Client.objects.get(user=user)
        client.coordinator = True   # set coordinator
        client.save()
        permission = Permission.objects.get(codename='coordinator')
        user.user_permissions.add(permission)
        group.user_set.add(client.user)  # add client to new group
        messages.success(self.request, Message.SUCCESS_SAVE)
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        """ Create client error """
        messages.error(self.request, form.errors)
        return self.render_to_response(self.get_context_data(form=form))


class ClientSearchGroupListView(LoginRequiredMixin, ListView):
    """ user group list """
    login_url = '/client/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'client/search_group.html'
    paginate_by = 5
    model = Group

    def get_queryset(self):
        filter_partial = Q()
        name = self.request.GET.get('name' or None)
        if name and name != '':
            partial_name = Q(name__icontains=name)
            filter_partial &= partial_name
        queryset = self.model.objects.filter(filter_partial)
        return queryset


class ClientGroupList(LoginRequiredMixin, SuccessMessageMixin, ListView):
    """ Shows group users  """
    login_url = '/client/login/'
    redirect_field_name = 'redirect_to'
    success_message = 'El usuario se agrego correctamente'
    template_name = 'client/user_group.html'
    model = Group

    def get_queryset(self):
        """ Show all group clients """
        group = self.model.objects.get(id=self.kwargs.get('pk'))
        account = Account.objects.filter(group=group)
        return account

    def get_context_data(self, **kwargs):
        context = super(ClientGroupList, self).get_context_data(**kwargs)
        group_count = self.model.objects.get(id=self.kwargs.get('pk')).user_set.all()
        user = User.objects.get(username=self.request.user)  # get user
        group = self.model.objects.get(id=self.kwargs.get('pk'))
        context['group_list'] = group.user_set.all()
        if user in group_count:
            context['member'] = True
        else:
            context['member'] = False
        if group_count.count() >= 4 and user.has_perm('client.coordinator'):
            new_account = True
        else:
            new_account = False
        context['group'] = group
        context['new_account'] = new_account
        return context

    def post(self, *args, **kwargs):
        group_count = self.model.objects.get(id=self.kwargs.get('pk')).user_set.all().count()
        if group_count >= 4:
            messages.error(self.request, 'El grupo solo puede contar con 4 integrantes')
        else:
            group = self.model.objects.get(id=self.kwargs.get('pk'))
            user = User.objects.get(username=self.request.user)  # get user
            group.user_set.add(user)  # add client to new group
            messages.success(self.request, Message.SUCCESS_SAVE)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))

templates/client/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/client/group.html
{%  extends 'base.html' %}

{% block section %}
    <section class="content-account">
    {% include 'client/partials/new_group.html' %}
    </section>
{% endblock %}

templates/client/login.html
{%  extends 'base.html' %}

{% block section %}
    <section class="content-account">
        <div class="paper paper-account">
            <form method="post">
                {% csrf_token %}
                <div class="content-row">
                    <span class="title title-account">Iniciar Seción</span>
                </div>
                <div class="content-row mt-2">
                    <div class="content-clm1">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="content-clm1">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    </div>
                </div>
                <div class="content-row mt-2">
                    <div class="content-clm1">
                        <button type="submit" class="btn btn-account btn-primary">
                            Iniciar Secion
                        </button>
                        <button type="button" class="btn btn-account btn-secondary">
                            <a href="{% url 'client:sign_up' %}">Registrarse</a>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

templates/client/new_group.html
{%  extends 'base.html' %}

{% block section %}
    <section class="content-account">
        <div class="paper paper-account">
        <form method="post" style="width:100%">
            {% csrf_token %}
            <div class="content-row">
                <span class="title title-account">Nuevo Grupo</span>
            </div>
            <div class="content-row mt-2">
                <div class="content-clm1">
                    {{ form.name.label_tag }}
                    {{ form.name }}
                </div>
            </div>
            <div class="content-row mt-2">
                <div class="content-clm1">
                    <button type="button" class="btn btn-account btn-primary">
                       <a href="{% url 'client:search_groups' %}">
                           Unirse a grupo
                       </a>
                    </button>
                    <button type="submit" class="btn btn-account btn-secondary">
                        Agregar nuevo
                    </button>
                </div>
            </div>
        </form>
    </div>
    </section>
{% endblock %}

templates/client/search_group.html
{%  extends 'base.html' %}

{% block section %}
    <section class="content-account">
        <div class="paper paper-group">
            <form method="get">
                {% csrf_token %}
                <div class="content-row">
                    <span class="title title-account">Buscar Grupo</span>
                </div>
                <div class="content-row mt-2">
                    <div class="content-clm1">
                        <label>Buscar Grupo</label>
                        <input class="field-account" type="text" name="name" id="id_name">
                    </div>
                    <div class="content-clm1 mt-1">
                        <button type="submit" class="btn btn-account btn-secondary">
                            Buscar Grupo
                        </button>
                        <button type="button" class="btn btn-account btn-primary">
                            <a href="{% url 'client:new_group' %}">
                                Crear grupo
                            </a>
                        </button>
                    </div>
                </div>
                <div class="content-row mt-2">
                    {% for item in object_list %}
                        <div class="content content-box">
                            <a href="{% url 'client:user_groups' item.id %}">
                                {{ item.name }}
                            </a>
                        </div>
                    {% empty %}
                    <div class="content content-box">
                        <span class="text">No se encontraron grupos</span>
                    </div>
                    {% endfor %}
                </div>
            </form>
        </div>
    </section>
{% endblock %}

templates/client/sign_up.html
{%  extends 'base.html' %}

{% block section %}
    <section class="content-account">
        <div class="paper paper-account">
            <form method="post">
                {% csrf_token %}
                <div class="content-row">
                    <span class="title title-account">Registrate</span>
                </div>
                <div class="content-row mt-2">
                    <div class="content-clm1">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="content-clm1">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    </div>
                    <div class="content-clm1">
                        {{ form.password1.label_tag }}
                        {{ form.password1 }}
                    </div>
                    <div class="content-clm1">
                        {{ form.password2.label_tag }}
                        {{ form.password2 }}
                    </div>
                    <div class="content-clm1">
                        {{ form.email.label_tag }}
                        {{ form.email }}
                    </div>
                </div>
                <div class="content-row mt-2">
                    <div class="content-clm1">
                        <button type="button" class="btn btn-account btn-primary">
                            <a href="{% url 'client:login' %}">Iniciar Secion</a>
                        </button>
                        <button type="submit" class="btn btn-account btn-secondary">
                            Registrarse
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

templates/client/user_group.html
{# template to request group registration #}

{%  extends 'base.html' %}
{% load permissiontag %}
{# template to request group registration #}

{% block section %}
    <section class="content-account">
        <div class="paper paper-group">
            <form method="post">
                {% csrf_token %}
                <div class="content-row">
                    <span class="title title-account"> {{ group.name }}</span>
                </div>
                <div class="content-row">
                    <span class="text">Usuario: {{ user.username }}</span>
                </div>
                <div class="content-row">
                    <span class="text">El grupo debe terner ucuatro integrantes para solicitar un prestamo</span>
                </div>
                <div class="content-row">
                    <span class="text">CLIENTES</span>
                </div>
                <div class="content-row">
                    {% for item in group_list %}
                        <div class="content content-box">
                            <span class="text"> {{ item.username }}</span>
                            {% if item|check_permission:'coordinator' %}
                                <span class="text">Coordinador</span>
                            {% endif %}
                        </div>
                    {% empty %}
                    <div class="content content-box">
                        <span class="text">No se encontraron participantes</span>
                    </div>
                    {% endfor %}
                </div>
                <div class="content-row mt-2">
                    <span class="text">CUENTAS</span>
                </div>
                <div class="content-row">
                    {% for item in object_list %}
                        <div class="content content-box">
                            <a href="{% url 'account:calendar' item.id %}">
                                <span class="text"> {{ item.amount }} - {{ item.status }}</span>
                            </a>
                        </div>
                    {% empty %}
                    <div class="content content-box">
                        <span class="text">Aun no tienen cuentas</span>
                    </div>
                    {% endfor %}
                </div>

                {% if not member %}
                <div class="content-row mt-2">
                    <div class="content-clm1 mt-1">
                        <button type="submit" class="btn btn-account btn-secondary">
                            Unirte al grupo
                        </button>
                    </div>
                </div>
                {% endif %}
                {% if new_account %}
                <div class="content-row mt-2">
                    <div class="content-clm1 mt-1">
                        <button type="button" class="btn btn-account btn-primary">
                            <a href="{% url 'account:new_account' group.id  %}">Solicitar Prestamo</a>
                        </button>
                    </div>
                </div>
                {% endif %}
            </form>
        </div>
    </section>
{% endblock %}